{{- if (index .Values "cert-manager" "enabled") }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "chart.fullname" . }}-ca
spec:
  isCA: true
  commonName: {{ include "chart.fullname" . }}
  secretName: {{ include "chart.fullname" . }}-root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ include "chart.fullname" . }}
    kind: ClusterIssuer
    group: cert-manager.io
{{- end -}}
