{{- if (index .Values "cert-manager" "enabled") }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "chart.fullname" . }}
spec:
  dnsNames:
  - {{ include "chart.fullname" . }}.{{ .Release.Namespace }}.svc
  - {{ include "chart.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "chart.fullname" . }}
  secretName: {{ include "chart.fullname" . }}
{{- end -}}
