name: "Integration tests"
on:
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jdxcode/rtx-action@v1
      - name: Deploy for CI
        run: |
          make ci
          kubectl port-forward svc/gke-tpu-env-injector 8000:443 &
          sleep 30
          curl --insecure https://localhost:8000/
