name: "Integration tests"
on:
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Should be kept up to date with supported GKE versions:
        # https://endoflife.date/google-kubernetes-engine
        kind-node:
          - kindest/node:v1.27.3
          - kindest/node:v1.26.6
          - kindest/node:v1.25.11
          - kindest/node:v1.24.15
    steps:
      - uses: actions/checkout@v3
      - uses: jdxcode/rtx-action@v1
      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          node_image: ${{ matrix.kind-node }}
      - run: |
          ./scripts/integration_test.sh
  test-complete:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: |
          echo "All tests passed!"
